### ISSUE TITLE
你好，我已部署成功，但在访问时候出现图片不加载的问题。在切换日夜模式后才会正常显示图片

### ISSUE THREAD

**Issue by A5yncX** [noyyyy/notion-faster-website#2]
[Hi, I’m AsyncX. Here is my archieves.](https://notion.asyncx.top/)

遇到的问题如题目所述。看到你的site.config.ts内将模糊图片加载改成了false，我也尝试了但是没用。

**Comment by A5yncX** [comment]
重新run了 可能是此项服务问题

**Comment by noyyyy** [comment]
> 重新run了 可能是此项服务问题

hi, @A5yncX ，你现在解决问题了吗

**Comment by A5yncX** [comment]
> hi, @A5yncX ，你现在解决问题了吗

解决啦，我重新build了一下页面，可能是第一次build出了问题，感谢。
